name: publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        flatbuffersVersion: ["1.11.0"]


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: pulynerain/gh-actions-flatbuffers@master
      with:
        flatbuffersVersion: ${{ matrix.flatbuffersVersion }}

    - name: bundle binaries
      run: tar czf '${{matrix.flatbuffersVersion}}.tar.gz' .flatbuffers

    - name: upload to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.flatbuffersVersion }}.tar.gz
        asset_name: ${{ matrix.flatbuffersVersion }}.tar.gz
        tag: ${{ github.ref }}
        overwrite: true